all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
all_joints_names:
- leftpaw
- leftankle
- leftknee
- tailbase
- tailtip
- rightknee
- rightankle
- rightpaw
- frontleftpaw
- frontleftelbow
- earleft
- mouth
- earright
- frontrightelbow
- frontrightpaw
- rodleft
- rodright
alpha_r: 0.02
apply_prob: 0.5
batch_size: 8
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
crop_sampling: hybrid
crop_size:
- 400
- 400
cropratio: 0.4
dataset: training-datasets/iteration-2/UnaugmentedDataSet_Trial9May23/Trial9_JDC95shuffle1.pickle
dataset_type: multi-animal-imgaug
decay_steps: 30000
display_iters: 500
global_scale: 0.8
init_weights: /usr/local/lib/python3.10/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets/iteration-2/UnaugmentedDataSet_Trial9May23/Documentation_data-Trial9_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: true
multi_step:
- - 0.0001
  - 7500
- - 5.0e-05
  - 12000
- - 1.0e-05
  - 200000
net_type: resnet_50
num_idchannel: 0
num_joints: 17
num_limbs: 45
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- - 4
  - 11
- - 1
  - 4
- - 3
  - 4
- - 4
  - 7
- - 4
  - 5
- - 7
  - 11
- - 0
  - 11
- - 11
  - 14
- - 2
  - 11
- - 3
  - 10
- - 3
  - 8
- - 1
  - 3
- - 8
  - 10
- - 1
  - 10
- - 0
  - 10
- - 9
  - 10
- - 6
  - 10
- - 6
  - 7
- - 7
  - 14
- - 7
  - 12
- - 2
  - 7
- - 7
  - 8
- - 5
  - 9
- - 5
  - 8
- - 2
  - 5
- - 9
  - 13
- - 9
  - 14
- - 9
  - 12
- - 1
  - 9
- - 8
  - 9
- - 6
  - 9
- - 1
  - 2
- - 1
  - 13
- - 1
  - 8
- - 0
  - 2
- - 2
  - 13
- - 2
  - 14
- - 0
  - 14
- - 0
  - 13
- - 6
  - 14
- - 6
  - 12
- - 6
  - 13
- - 13
  - 14
- - 8
  - 12
- - 12
  - 14
partaffinityfield_predict: true
pos_dist_thresh: 17
pre_resize: []
project_path: /content/drive/Shareddrives/dlc_udape/Trial9B-JDC-2022-05-23
rotation: 25
rotratio: 0.4
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
weigh_only_present_joints: false
